<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Faker\Generator;
use Illuminate\Container\Container;


class ProductSeeder extends Seeder
{
    protected $faker;

    public function __construct()
    {
        $this->faker = $this->withFaker();
    }

    protected function withFaker()
    {
        return Container::getInstance()->make(Generator::class);
    }

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = [
            "ABA_001" =>	"Aceite comestibles",
            "ABA_002" =>	"Aderezos",
            "ABA_003" =>	"Consome",
            "ABA_004" =>	"Crema de cacahuate",
            "ABA_005" =>	"Crema para café",
            "ABA_006" =>	"Pure de tomate",
            "ABA_007" =>	"Alimento para bebe",
            "ABA_008" =>	"Alimento para mascotas",
            "ABA_009" =>	"Atole",
            "ABA_010" =>	"Avena",
            "ABA_011" =>	"Azúcar",
            "ABA_012" =>	"Café",
            "ABA_013" =>	"Cereales",
            "ABA_014" =>	"Chile piquín",
            "ABA_015" =>	"Especias",
            "ABA_016" =>	"Flan en polvo",
            "ABA_017" =>	"Formulas infantiles",
            "ABA_018" =>	"Gelatinas en polvo/Grenetina",
            "ABA_019" =>	"Harina",
            "ABA_020" =>	"Harina preparada",
            "ABA_021" =>	"Mole",
            "ABA_022" =>	"Sal",
            "ABA_023" =>	"Salsas envasadas",
            "ABA_024" =>	"Sazonadores",
            "ABA_025" =>	"Sopas en sobre",
            "ABA_026" =>	"Cajeta",
            "ABA_027" =>	"Catsup",
            "ABA_028" =>	"Mayonesa",
            "ABA_029" =>	"Mermelada",
            "ABA_030" =>	"Miel",
            "ABA_031" =>	"Te",
            "ABA_032" =>	"Vinagre",
            "ABA_033" =>	"Huevo",
            "ABA_034" =>	"Pastas",
            "ENL_001" =>	"Aceitunas",
            "ENL_002" =>	"Champiñones enteros/rebanados",
            "ENL_003" =>	"Chícharo con zanahoria",
            "ENL_004" =>	"Chícharos enlatados",
            "ENL_005" =>	"Frijoles enlatados",
            "ENL_006" =>	"Frutas en almíbar",
            "ENL_007" =>	"Sardinas",
            "ENL_008" =>	"Atún en agua/aceite",
            "ENL_009" =>	"Chiles enlatados",
            "ENL_010" =>	"Chiles envasados",
            "ENL_011" =>	"Ensaladas enlatadas",
            "ENL_012" =>	"Granos de elote enlatados",
            "ENL_013" =>	"Sopa en lata",
            "ENL_014" =>	"Vegetales en conserva",
            "LAC_001" =>	"Leche condesada",
            "LAC_002" =>	"Leche deslactosada",
            "LAC_003" =>	"Leche en polvo",
            "LAC_004" =>	"Leche evaporada",
            "LAC_005" =>	"Leche light",
            "LAC_006" =>	"Leche pasteurizada",
            "LAC_007" =>	"Leche saborizada",
            "LAC_008" =>	"Leche semidescremada",
            "LAC_009" =>	"Crema",
            "LAC_010" =>	"Yoghurt",
            "LAC_011" =>	"Mantequilla",
            "LAC_012" =>	"Margarina",
            "LAC_013" =>	"Media crema",
            "LAC_014" =>	"Queso",
            "BOT_001" =>	"Papa",
            "BOT_002" =>	"Palomitas",
            "BOT_003" =>	"Frituras de maíz",
            "BOT_004" =>	"Cacahuates",
            "BOT_005" =>	"Botanas saladas",
            "BOT_006" =>	"Barras alimenticias",
            "BOT_007" =>	"Nueces y semillas",
            "CON_001" =>	"Caramelos",
            "CON_002" =>	"Dulces enchilados",
            "CON_003" =>	"Chocolate de mesa",
            "CON_004" =>	"Chocolate en polvo",
            "CON_005" =>	"Chocolates",
            "CON_006" =>	"Gomas de mascar",
            "CON_007" =>	"Mazapán",
            "CON_008" =>	"Malvaviscos",
            "CON_009" =>	"Pulpa de tamarindo",
            "CON_010" =>	"Pastillas de dulce",
            "CON_011" =>	"Paletas de dulce",
            "HAR_001" =>	"Tortillas de harina/maíz",
            "HAR_002" =>	"Galletas dulces",
            "HAR_003" =>	"Galletas saladas",
            "HAR_004" =>	"Pastelillos",
            "HAR_005" =>	"Pan de caja",
            "HAR_006" =>	"Pan dulce",
            "HAR_007" =>	"Pan molido",
            "HAR_008" =>	"Pan tostado",
            "FRU_001" =>	"Aguacates",
            "FRU_002" =>	"Ajos",
            "FRU_003" =>	"Cebollas",
            "FRU_004" =>	"Chiles",
            "FRU_005" =>	"Cilantro/Perejil",
            "FRU_006" =>	"Jitomate",
            "FRU_007" =>	"Papas",
            "FRU_008" =>	"Limones",
            "FRU_009" =>	"Manzanas",
            "FRU_010" =>	"Naranjas",
            "FRU_011" =>	"Plátanos",
            "BEB_001" =>	"Agua mineral",
            "BEB_002" =>	"Agua natural",
            "BEB_003" =>	"Agua saborizada",
            "BEB_004" =>	"Jarabes",
            "BEB_005" =>	"Jugos/Néctares",
            "BEB_006" =>	"Naranjadas",
            "BEB_007" =>	"Bebidas de soya",
            "BEB_008" =>	"Bebidas en polvo",
            "BEB_009" =>	"Bebidas infantiles",
            "BEB_010" =>	"Bebidas isotónicas",
            "BEB_011" =>	"Energetizantes",
            "BEB_012" =>	"Isotónicos",
            "BEB_013" =>	"Refrescos",
            "BEB_014" =>	"Bebidas preparadas",
            "BEB_015" =>	"Cerveza",
            "BEB_016" =>	"Anís",
            "BEB_017" =>	"Brandy",
            "BEB_018" =>	"Ginebra",
            "BEB_019" =>	"Cordiales",
            "BEB_020" =>	"Mezcal",
            "BEB_021" =>	"Jerez",
            "BEB_022" =>	"Ron",
            "BEB_023" =>	"Tequila",
            "BEB_024" =>	"Sidra",
            "BEB_025" =>	"Whiskey",
            "BEB_026" =>	"Vodka",
            "ALI_001" =>	"Pastas listas para comer",
            "ALI_002" =>	"Sopas en vaso",
            "ALI_003" =>	"Carnes y Embudos",
            "ALI_004" =>	"Salchicha",
            "ALI_005" =>	"Mortadela",
            "ALI_006" =>	"Tocino",
            "ALI_007" =>	"Jamón",
            "ALI_008" =>	"Manteca",
            "ALI_009" =>	"Chorizo",
            "ALI_010" =>	"Carne de puerco/res/pollo",
            "MED_001" =>	"Suero",
            "MED_002" =>	"Agua oxigenada",
            "MED_003" =>	"Preservativos",
            "MED_004" =>	"Alcohol",
            "MED_005" =>	"Gasas",
            "MED_006" =>	"Analgésicos",
            "MED_007" =>	"Antigripales",
            "MED_008" =>	"Antiácidos",
            "HIG_001" =>	"Toallas húmedas",
            "HIG_002" =>	"Aceite para bebe",
            "HIG_003" =>	"Toallas femeninas",
            "HIG_004" =>	"Algodón",
            "HIG_005" =>	"Tinte para el cabello",
            "HIG_006" =>	"Biberones",
            "HIG_007" =>	"Talco",
            "HIG_008" =>	"Cepillo de dientes",
            "HIG_009" =>	"Shampoo/ Acondicionador",
            "HIG_010" =>	"Cotonetes",
            "HIG_011" =>	"Rastrillos",
            "HIG_012" =>	"Crema corporal/facial",
            "HIG_013" =>	"Papel higiénico",
            "HIG_014" =>	"Crema para afeitar",
            "HIG_015" =>	"Pañuelos faciales",
            "HIG_016" =>	"Dentífricos",
            "HIG_017" =>	"Pañuelos desechables",
            "HIG_018" =>	"Desodorantes en barra/aerosol",
            "HIG_019" =>	"Maquillaje",
            "HIG_020" =>	"Enjuague bucal",
            "HIG_021" =>	"Lubricantes para labios",
            "HIG_022" =>	"Gel/spray",
            "HIG_023" =>	"Loción hidratante",
            "HIG_024" =>	"Jabones corporales/tocados",
            "DOM_001" =>	"Suavizante de telas",
            "DOM_002" =>	"Ácido muriático",
            "DOM_003" =>	"Sosa caustica",
            "DOM_004" =>	"Aluminio",
            "DOM_005" =>	"Pilas",
            "DOM_006" =>	"Shampoo para ropa",
            "DOM_007" =>	"Servilletas",
            "DOM_008" =>	"Servitoallas",
            "DOM_009" =>	"Aromatizantes",
            "DOM_010" =>	"Cera para automóvil",
            "DOM_011" =>	"Cera para calzados",
            "DOM_012" =>	"Pastillas sanitarias",
            "DOM_013" =>	"Limpiadores líquidos",
            "DOM_014" =>	"Limpiadores para pisos",
            "DOM_015" =>	"Jabón de barra",
            "DOM_016" =>	"Cerillos",
            "DOM_017" =>	"Cloro/Blanqueador",
            "DOM_018" =>	"Cloro para ropa",
            "DOM_019" =>	"Jabón en barra",
            "DOM_020" =>	"Insecticidas",
            "DOM_021" =>	"Fibras limpiadoras",
            "DOM_022" =>	"Desinfectantes",
            "DOM_023" =>	"Detergentes para trastes",
            "DOM_024" =>	"Detergente para ropa",
            "HEL_001" =>	"Paletas/ Helados",
            "JAR_001" =>	"Veladoras/Velas",
            "JAR_002" =>	"Cepillo de plástico",
            "JAR_003" =>	"Vasos desechables",
            "JAR_004" =>	"Cinta adhesiva",
            "JAR_005" =>	"Cucharas de plástico",
            "JAR_006" =>	"Escobas/Trapeadores/Mechudos",
            "JAR_007" =>	"Trampas para ratas",
            "JAR_008" =>	"Tenedores de plástico",
            "JAR_009" =>	"Extensiones/Multicontacto",
            "JAR_010" =>	"Recogedor de metal/plástico",
            "JAR_011" =>	"Popotes",
            "JAR_012" =>	"Platos desechables",
            "JAR_013" =>	"Focos",
            "JAR_014" =>	"Fusibles",
            "JAR_015" =>	"Jergas/Franelas",
            "JAR_016" =>	"Matamoscas",
            "JAR_017" =>	"Pegamento",
            "JAR_018" =>	"Mecate/cuerda",
            "OTR_001" =>	"Tarjetas telefónicas",
            "OTR_002" =>	"Recargas móviles",
            "OTR_003" =>	"Hielo",
            "OTR_004" =>	"Cigarros"
        ];

        Schema::disableForeignKeyConstraints();
        DB::table('products')->truncate();
        Schema::enableForeignKeyConstraints();

        foreach ($products as $key=>$item) {
            $product = new Product();
            $product->product = $item;
            $product->product_code = $key;
            $product->price = $this->faker->numberBetween($min = 1000, $max = 10000);

            $product->save();
        }
    }
}
